/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package setting;

/**
 *
 * @author tug70
 */
public class SettingUI extends javax.swing.JPanel {
    private static boolean ProjectEditToggle;
    private static boolean SprintEditToggle;
    private static boolean TeamEditToggle;
    /**
     * Creates new form settingUI
     */
    public SettingUI() {
        initComponents();
        ProjectEditToggle=false;
        SprintEditToggle=false;
        TeamEditToggle=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditProject = new javax.swing.JButton();
        editSprint = new javax.swing.JToggleButton();
        editTeam = new javax.swing.JToggleButton();

        EditProject.setText("edit project");
        EditProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProjectActionPerformed(evt);
            }
        });

        editSprint.setText("edit sprint");
        editSprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSprintActionPerformed(evt);
            }
        });

        editTeam.setText("edit team");
        editTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EditProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editSprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditProject)
                .addGap(18, 18, 18)
                .addComponent(editSprint)
                .addGap(18, 18, 18)
                .addComponent(editTeam)
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EditProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProjectActionPerformed
        setProjectEditToggle(!isProjectEditToggle());
       
    }//GEN-LAST:event_EditProjectActionPerformed

    private void editSprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSprintActionPerformed
       setSprintEditToggle(!isSprintEditToggle());
    }//GEN-LAST:event_editSprintActionPerformed

    private void editTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTeamActionPerformed
        setTeamEditToggle(!isTeamEditToggle());
    }//GEN-LAST:event_editTeamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditProject;
    private javax.swing.JToggleButton editSprint;
    private javax.swing.JToggleButton editTeam;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ProjectEditToggle
     */
    public static boolean isProjectEditToggle() {
        return ProjectEditToggle;
    }

    /**
     * @param aProjectEditToggle the ProjectEditToggle to set
     */
    public static void setProjectEditToggle(boolean aProjectEditToggle) {
        ProjectEditToggle = aProjectEditToggle;
    }

    /**
     * @return the SprintEditToggle
     */
    public static boolean isSprintEditToggle() {
        return SprintEditToggle;
    }

    /**
     * @param aSprintEditToggle the SprintEditToggle to set
     */
    public static void setSprintEditToggle(boolean aSprintEditToggle) {
        SprintEditToggle = aSprintEditToggle;
    }

    /**
     * @return the TeamEditToggle
     */
    public static boolean isTeamEditToggle() {
        return TeamEditToggle;
    }

    /**
     * @param aTeamEditToggle the TeamEditToggle to set
     */
    public static void setTeamEditToggle(boolean aTeamEditToggle) {
        TeamEditToggle = aTeamEditToggle;
    }
}
