/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout.views.CommentUI;

import common.Enum.TaskStatus;
import common.Ultilities.Utilities;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author tug70
 */
public class CommentUI extends javax.swing.JPanel {

    /**
     * Creates new form CommentUI
     */
    public CommentUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateDate = new javax.swing.JLabel();
        commentPanel = new javax.swing.JPanel();
        commentString = new javax.swing.JLabel();
        taskStatusEnum = new javax.swing.JLabel();
        profilePic = new javax.swing.JLabel();

        dateDate.setText("date");

        commentString.setText("comment");

        taskStatusEnum.setText("taskStatus");

        javax.swing.GroupLayout commentPanelLayout = new javax.swing.GroupLayout(commentPanel);
        commentPanel.setLayout(commentPanelLayout);
        commentPanelLayout.setHorizontalGroup(
            commentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(commentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(commentString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profilePic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(taskStatusEnum)
                .addGap(25, 25, 25))
        );
        commentPanelLayout.setVerticalGroup(
            commentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commentPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(commentString)
                .addGap(11, 11, 11)
                .addGroup(commentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(taskStatusEnum)
                    .addComponent(profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateDate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(commentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dateDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(commentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel commentPanel;
    private javax.swing.JLabel commentString;
    private javax.swing.JLabel dateDate;
    private javax.swing.JLabel profilePic;
    private javax.swing.JLabel taskStatusEnum;
    // End of variables declaration//GEN-END:variables

    public void renderUI(int num) {
        
    }

    /**
     * @return the commentString
     */
    public javax.swing.JLabel getCommentString() {
        return commentString;
    }

    /**
     * @param commentString the commentString to set
     */
    public void setCommentString(String commentString) {
        this.commentString.setText(commentString);
    }

    /**
     * @return the dateDate
     */
    public javax.swing.JLabel getDateDate() {
        return dateDate;
    }

    /**
     * @param dateDate the dateDate to set
     */
    public void setDateDate(Date dateDate) {
        this.dateDate.setText(Utilities.getDateString(dateDate));
    }

    /**
     * @return the profilePic
     */
    public javax.swing.JLabel getProfilePic() {
        return profilePic;
    }

    /**
     * @param profilePic the profilePic to set
     */
    public void setProfilePic(String profilePic) {
        ImageIcon icon = new ImageIcon(profilePic);
        icon = new ImageIcon(icon.getImage().getScaledInstance(53, 51,  java.awt.Image.SCALE_SMOOTH)); 
        this.profilePic.setIcon(icon);
    }

    /**
     * @return the taskStatusEnum
     */
    public javax.swing.JLabel getTaskStatusEnum() {
        return taskStatusEnum;
    }

    /**
     * @param taskStatusEnum the taskStatusEnum to set
     */
    public void setTaskStatusEnum(TaskStatus taskStatusEnum) {
        this.taskStatusEnum.setText(taskStatusEnum.name());
    }
}
