/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout.views.team;

import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.awt.Toolkit;

/**
 *
 * @author tug70
 */
public class SendEmailUI extends javax.swing.JFrame {

    /**
     * Creates new form SendEmail
     */
    public SendEmailUI() {
    	setTitle("Bug Tracker 3000 - Send Email");
    	setIconImage(Toolkit.getDefaultToolkit().getImage(SendEmailUI.class.getResource("/layout/resource/BugTracker.png")));
        initComponents();
        this.getErrorText().setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toString = new javax.swing.JTextField();
        titleString = new javax.swing.JTextField();
        fromString = new javax.swing.JTextField();
        toLabel = new javax.swing.JLabel();
        sendEmailLabel = new javax.swing.JLabel();
        buttonSection = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        contentlLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emailContentArea = new javax.swing.JTextArea();
        errorText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toString.setEditable(false);

        fromString.setEditable(false);

        toLabel.setText("To:");

        sendEmailLabel.setText("SEND EMAIL");

        submitButton.setText("send");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonSectionLayout = new javax.swing.GroupLayout(buttonSection);
        buttonSection.setLayout(buttonSectionLayout);
        buttonSectionLayout.setHorizontalGroup(
            buttonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonSectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addGap(6, 6, 6))
        );
        buttonSectionLayout.setVerticalGroup(
            buttonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonSectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        titleLabel.setText("Title");

        contentlLabel.setText("Content:");

        fromLabel.setText("From");

        emailContentArea.setColumns(20);
        emailContentArea.setRows(5);
        jScrollPane1.setViewportView(emailContentArea);

        errorText.setForeground(new java.awt.Color(255, 51, 51));
        errorText.setText("error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonSection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(errorText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(sendEmailLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleLabel)
                                    .addComponent(fromLabel)
                                    .addComponent(toLabel))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fromString, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(toString)
                                    .addComponent(titleString)))
                            .addComponent(contentlLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sendEmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorText)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromLabel)
                    .addComponent(fromString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toLabel)
                    .addComponent(toString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contentlLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(buttonSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //TODO, get a better email address
        // Recipient's email ID needs to be mentioned.
        //String to = this.getToString().getText();
        String to = "tug64107@temple.edu";

        // Sender's email ID needs to be mentioned
        String from = "uekikosuke21@gmail.com";
        String password = "Uekikosuke21";

        // Assuming you are sending email from localhost
        String host = "localhost";

        // Get system properties
        Properties properties = System.getProperties();

        // Setup mail server
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.post", "465");
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.socketFactory.port", "465");
        properties.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        properties.put("mail.smtp.ssl.enable", "true");
        
        // Get the default Session object.
        //Session session = Session.getDefaultInstance(properties);
        Session session = Session.getInstance(properties, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(from, password);
            }
        });
        
        
        String title=this.getTitleString().getText();
        String email=this.getEmailContentArea().getText();
        if(!title.isEmpty()&&!email.isEmpty()){
        try {
            // Create a default MimeMessage object.
            MimeMessage message = new MimeMessage(session);

            // Set From: header field of the header.
            message.setFrom(new InternetAddress(from));

            // Set To: header field of the header.
            //message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(to));

            // Set Subject: header field
            message.setSubject(title);

            // Now set the actual message
            message.setText(email);

            // Send message
            Transport.send(message);
            System.out.println("Sent message successfully....");
        } catch (MessagingException mex) {
            this.setErrorText("there's some error, please try again");
            mex.printStackTrace();
        }
        this.dispose();
        }
        else{
            this.setErrorText("please input title or email message");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
       this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendEmailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendEmailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendEmailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendEmailUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendEmailUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonSection;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel contentlLabel;
    private javax.swing.JTextArea emailContentArea;
    private javax.swing.JLabel errorText;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JTextField fromString;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sendEmailLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleString;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField toString;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the buttonSection
     */
    public javax.swing.JPanel getButtonSection() {
        return buttonSection;
    }

    /**
     * @param buttonSection the buttonSection to set
     */
    public void setButtonSection(javax.swing.JPanel buttonSection) {
        this.buttonSection = buttonSection;
    }

    /**
     * @return the cancelButton
     */
    public javax.swing.JButton getCancelButton() {
        return cancelButton;
    }

    /**
     * @param cancelButton the cancelButton to set
     */
    public void setCancelButton(javax.swing.JButton cancelButton) {
        this.cancelButton = cancelButton;
    }

    /**
     * @return the contentlLabel
     */
    public javax.swing.JLabel getContentlLabel() {
        return contentlLabel;
    }

    /**
     * @param contentlLabel the contentlLabel to set
     */
    public void setContentlLabel(javax.swing.JLabel contentlLabel) {
        this.contentlLabel = contentlLabel;
    }

    /**
     * @return the emailContentArea
     */
    public javax.swing.JTextArea getEmailContentArea() {
        return emailContentArea;
    }

    /**
     * @param emailContentArea the emailContentArea to set
     */
    public void setEmailContentArea(javax.swing.JTextArea emailContentArea) {
        this.emailContentArea = emailContentArea;
    }

    /**
     * @return the errorText
     */
    public javax.swing.JLabel getErrorText() {
        return errorText;
    }

    /**
     * @param errorText the errorText to set
     */
    public void setErrorText(String errorText) {
        this.errorText.setText(errorText);
    }

    /**
     * @return the fromLabel
     */
    public javax.swing.JLabel getFromLabel() {
        return fromLabel;
    }

    /**
     * @param fromLabel the fromLabel to set
     */
    public void setFromLabel(javax.swing.JLabel fromLabel) {
        this.fromLabel = fromLabel;
    }

    /**
     * @return the fromString
     */
    public javax.swing.JTextField getFromString() {
        return fromString;
    }

    /**
     * @param fromString the fromString to set
     */
    public void setFromString(String fromString) {
        this.fromString.setText(fromString);
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the sendEmailLabel
     */
    public javax.swing.JLabel getSendEmailLabel() {
        return sendEmailLabel;
    }

    /**
     * @param sendEmailLabel the sendEmailLabel to set
     */
    public void setSendEmailLabel(javax.swing.JLabel sendEmailLabel) {
        this.sendEmailLabel = sendEmailLabel;
    }

    /**
     * @return the submitButton
     */
    public javax.swing.JButton getSubmitButton() {
        return submitButton;
    }

    /**
     * @param submitButton the submitButton to set
     */
    public void setSubmitButton(javax.swing.JButton submitButton) {
        this.submitButton = submitButton;
    }

    /**
     * @return the titleLabel
     */
    public javax.swing.JLabel getTitleLabel() {
        return titleLabel;
    }

    /**
     * @param titleLabel the titleLabel to set
     */
    public void setTitleLabel(javax.swing.JLabel titleLabel) {
        this.titleLabel = titleLabel;
    }

    /**
     * @return the titleString
     */
    public javax.swing.JTextField getTitleString() {
        return titleString;
    }

    /**
     * @param titleString the titleString to set
     */
    public void setTitleString(javax.swing.JTextField titleString) {
        this.titleString = titleString;
    }

    /**
     * @return the toLabel
     */
    public javax.swing.JLabel getToLabel() {
        return toLabel;
    }

    /**
     * @param toLabel the toLabel to set
     */
    public void setToLabel(javax.swing.JLabel toLabel) {
        this.toLabel = toLabel;
    }

    /**
     * @return the toString
     */
    public javax.swing.JTextField getToString() {
        return toString;
    }

    /**
     * @param toString the toString to set
     */
    public void setToString(String toString) {
        this.toString.setText(toString);
    }
}
