/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen;
import java.awt.*;
import javax.swing.*;
import user.UserUI;
import java.util.Arrays;
import project.ProjectUIDropdown;
import sprint.SprintUIDropdown;
import user.TeamUIDropdown;
import user.UserUIDropdown;
/**
 *
 * @author tug70
 */
public class ScreenUI extends javax.swing.JFrame{

    /**
     * Creates new form ScreenUI
     */
    public ScreenUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dropDownsHolder = new javax.swing.JPanel();
        productName = new javax.swing.JLabel();
        boardsHolder = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dev Screen");
        setBounds(new java.awt.Rectangle(50, 10, 100, 100));
        setMaximumSize(new java.awt.Dimension(1400, 1400));
        setPreferredSize(new java.awt.Dimension(1800, 1000));

        javax.swing.GroupLayout dropDownsHolderLayout = new javax.swing.GroupLayout(dropDownsHolder);
        dropDownsHolder.setLayout(dropDownsHolderLayout);
        dropDownsHolderLayout.setHorizontalGroup(
            dropDownsHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1625, Short.MAX_VALUE)
        );
        dropDownsHolderLayout.setVerticalGroup(
            dropDownsHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        productName.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        productName.setForeground(new java.awt.Color(255, 102, 102));
        productName.setText("BUG TRACKER 3000");

        javax.swing.GroupLayout boardsHolderLayout = new javax.swing.GroupLayout(boardsHolder);
        boardsHolder.setLayout(boardsHolderLayout);
        boardsHolderLayout.setHorizontalGroup(
            boardsHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        boardsHolderLayout.setVerticalGroup(
            boardsHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1218, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dropDownsHolder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boardsHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(productName)
                .addGap(666, 666, 666))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dropDownsHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boardsHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void displayJFrame(){
        UserUIDropdown userUI = new UserUIDropdown();
        ProjectUIDropdown projectUI= new ProjectUIDropdown();
        TeamUIDropdown teamUI =new TeamUIDropdown();
        SprintUIDropdown sprintUI = new SprintUIDropdown();
        JPanel j=new JPanel();
        //JPanel j1=new JPanel();
        j.add(userUI);
        //row 1
        dropDownsHolder.add(projectUI);
        //dropDownsHolder.add(j);
        dropDownsHolder.add(sprintUI);
        //row 2
        dropDownsHolder.add(teamUI);
        //dropDownsHolder.add(j1);
        dropDownsHolder.add(j);
        
        
        this.pack();
        GridLayout layout=new GridLayout(2, 2);
        projectUI.setLayout(new FlowLayout(FlowLayout.LEFT));
        j.setLayout(new FlowLayout(FlowLayout.RIGHT));
        sprintUI.setLayout(new FlowLayout(FlowLayout.RIGHT));
        teamUI.setLayout(new FlowLayout(FlowLayout.LEFT));
        dropDownsHolder.setLayout(layout);
        dropDownsHolder.setBorder(BorderFactory.createEmptyBorder(0, 100, 0, 100));
        this.setVisible(true);
        
        
    }
     
    public static void displayProjectCreate(boolean display){
        
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardsHolder;
    private javax.swing.JPanel dropDownsHolder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel productName;
    // End of variables declaration//GEN-END:variables
}
