/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout.views.user;

import java.awt.Color;

import common.User.CurrentUserhold;
import layout.views.AlertUI.AlertUI;
import layout.views.LogInUI.LogInUI;
import layout.views.screen.ScreenUI;

/**
 *
 * @author tug70
 */
public class UserUIDropdown extends javax.swing.JPanel {
    private static boolean isLogIn;
    /**
     * Creates new form UserUIDropdown
     */
    public UserUIDropdown() {
        initComponents();
        renderUI();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authentication = new javax.swing.JButton();
        userUI = new layout.views.user.UserUI();

        setPreferredSize(new java.awt.Dimension(210, 120));
        setLayout(new java.awt.BorderLayout());

        authentication.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        authentication.setText("Log in");
        authentication.setMaximumSize(new java.awt.Dimension(300, 25));
        authentication.setPreferredSize(new java.awt.Dimension(300, 20));
        authentication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenticationActionPerformed(evt);
            }
        });
        add(authentication, java.awt.BorderLayout.PAGE_START);
        add(userUI, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void authenticationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenticationActionPerformed
        if(getAuthentication().getText().equals("Log out")){
            getAuthentication().setText("Log in");
            //getUserUI().setVisible(false);
            CurrentUserhold.setUser(null);
            ScreenUI.getAlertButton().setForeground(Color.BLACK);
            ScreenUI.getLayoutUI().addTask();
            ScreenUI.renderUI();
        }
        else if(getAuthentication().getText().equals("Log in")){
            LogInUI loginform= new LogInUI();
            loginform.setVisible(true);
            //no need for rerender board here. Rerender board is called at log in
            
        }
    }//GEN-LAST:event_authenticationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authentication;
    private static layout.views.user.UserUI userUI;
    // End of variables declaration//GEN-END:variables
    


    public void renderUI(){
        //UserUIDropdown.setUserUI(new UserUI());
       // UserUIDropdown.getUserUI().setUserFromDatabase(7);
        //cuurent user already get set as this method is called but not before
        if(CurrentUserhold.getUser()!=null){
        UserUIDropdown.getUserUI().setUserFromDatabase(CurrentUserhold.getUser().getID()-1);
        }
        else{
            UserUIDropdown.getUserUI().setUserAtNull();
        }
        
    }

    /**E
     * @return the userUI
     */
    public static UserUI getUserUI() {
        return userUI;
    }

    /**
     * @param aUserUI the userUI to set
     */
    public static void setUserUI(UserUI aUserUI) {
        userUI = aUserUI;
    }
    
    
    /**
     * @return the isLogIn
     */
    public static boolean isIsLogIn() {
        return isLogIn;
    }

    /**
     * @param aIsLogIn the isLogIn to set
     */
    public static void setIsLogIn(boolean aIsLogIn) {
        isLogIn = aIsLogIn;
    }

    /**
     * @return the authentication
     */
    public javax.swing.JButton getAuthentication() {
        return authentication;
    }

    /**
     * @param authentication the authentication to set
     */
    public void setAuthentication(javax.swing.JButton authentication) {
        this.authentication = authentication;
    }
    
}

