/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout.views.layout;

import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;

import common.Comment.CommentsAllHold;
import layout.views.FilterUI.FilterUI;
import layout.views.SortUI.SortUI;
import common.Enum.BoardType;
import common.User.CurrentUserhold;
import layout.views.BoardUI.BoardUI;
import layout.views.TaskUI.TaskCreate;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Dimension;

/**
 *
 * @author tug70
 */
public class LayoutUI extends javax.swing.JPanel {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Layout
     */
    public LayoutUI() {

        initComponents();
        setPMinimizeHidden();
        addTask();
    }
    private BoardUI backlog;
    private BoardUI taken;
    private BoardUI ongoing;
    private BoardUI finish;

    public void addLog() {

        backlog = new BoardUI(BoardType.BACKLOG);
        taken = new BoardUI(BoardType.TAKEN);
        ongoing = new BoardUI(BoardType.ONGOING);
        finish = new BoardUI(BoardType.FINISH);

        getBacklog().addContainerListener(new componentChangeListener());
        getTaken().addContainerListener(new componentChangeListener());
        getOngoing().addContainerListener(new componentChangeListener());
        getFinish().addContainerListener(new componentChangeListener());
    }

    public void rerenderAllBoard() {
        //backlog.refresh();
        //taken.refresh();
        //ongoing.refresh();
        getFinish().refresh();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        LeftProjectPanel = new javax.swing.JPanel();
        SearchBarL = new javax.swing.JTextField();
        SearchIconL = new javax.swing.JButton();
        OnBacklogPanel = new javax.swing.JScrollPane();
        SortL = new javax.swing.JButton();
        FilterL = new javax.swing.JButton();
        AddTaskButton = new javax.swing.JButton();
        MinimizeButtonL = new javax.swing.JButton();
        MidProjectPanel = new javax.swing.JPanel();
        MinimizeButtonM = new javax.swing.JButton();
        MaximizeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DeMaximizeButton = new javax.swing.JButton();
        ProgressBoardButton = new javax.swing.JButton();
        MemberBoardButton = new javax.swing.JButton();
        OnTakenPanel = new javax.swing.JScrollPane();
        OnGoingPanel = new javax.swing.JScrollPane();
        RightProjectPanel = new javax.swing.JPanel();
        SearchIconR = new javax.swing.JButton();
        SearchBarR = new javax.swing.JTextField();
        OnFinishPanel = new javax.swing.JScrollPane();
        MinimizeButtonR = new javax.swing.JButton();
        filterR = new javax.swing.JButton();
        sortR = new javax.swing.JButton();
        DeMinimizeButtonR = new javax.swing.JButton();
        DeMinimizeButtonL = new javax.swing.JButton();
        DeMinimizeButtonM = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1400, 600));

        LeftProjectPanel.setBackground(new java.awt.Color(0, 153, 204));

        SearchBarL.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        SearchIconL.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        SearchIconL.setText("search");
        SearchIconL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIconLActionPerformed(evt);
            }
        });

        OnBacklogPanel.setPreferredSize(new java.awt.Dimension(300, 450));

        SortL.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        SortL.setText("sort");
        SortL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortLActionPerformed(evt);
            }
        });

        FilterL.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        FilterL.setText("filter");
        FilterL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterLActionPerformed(evt);
            }
        });

        AddTaskButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        AddTaskButton.setText("add");
        AddTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskButtonActionPerformed(evt);
            }
        });

        MinimizeButtonL.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        MinimizeButtonL.setText("< <");
        MinimizeButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftProjectPanelLayout = new javax.swing.GroupLayout(LeftProjectPanel);
        LeftProjectPanel.setLayout(LeftProjectPanelLayout);
        LeftProjectPanelLayout.setHorizontalGroup(
            LeftProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftProjectPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinimizeButtonL))
            .addGroup(LeftProjectPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(LeftProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OnBacklogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LeftProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(LeftProjectPanelLayout.createSequentialGroup()
                            .addComponent(AddTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(SortL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(55, 55, 55)
                            .addComponent(FilterL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(LeftProjectPanelLayout.createSequentialGroup()
                            .addComponent(SearchBarL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SearchIconL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        LeftProjectPanelLayout.setVerticalGroup(
            LeftProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftProjectPanelLayout.createSequentialGroup()
                .addComponent(MinimizeButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LeftProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBarL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchIconL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OnBacklogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LeftProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SortL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FilterL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        MidProjectPanel.setBackground(new java.awt.Color(255, 204, 51));

        MinimizeButtonM.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        MinimizeButtonM.setText(">> <<");
        MinimizeButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonMActionPerformed(evt);
            }
        });

        MaximizeButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        MaximizeButton.setText("< >");
        MaximizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaximizeButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Ontaken");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("Ongoing");

        DeMaximizeButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        DeMaximizeButton.setText("> <");
        DeMaximizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMaximizeButtonActionPerformed(evt);
            }
        });

        ProgressBoardButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ProgressBoardButton.setText("Progress Board");
        ProgressBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgressBoardButtonActionPerformed(evt);
            }
        });

        MemberBoardButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        MemberBoardButton.setText("Member Board");
        MemberBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberBoardButtonActionPerformed(evt);
            }
        });

        OnTakenPanel.setPreferredSize(new java.awt.Dimension(300, 450));

        OnGoingPanel.setPreferredSize(new java.awt.Dimension(300, 450));

        javax.swing.GroupLayout MidProjectPanelLayout = new javax.swing.GroupLayout(MidProjectPanel);
        MidProjectPanel.setLayout(MidProjectPanelLayout);
        MidProjectPanelLayout.setHorizontalGroup(
            MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MidProjectPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MidProjectPanelLayout.createSequentialGroup()
                        .addGroup(MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OnTakenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(OnGoingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MidProjectPanelLayout.createSequentialGroup()
                        .addComponent(MaximizeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeMaximizeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinimizeButtonM))
                    .addGroup(MidProjectPanelLayout.createSequentialGroup()
                        .addComponent(ProgressBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MemberBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        MidProjectPanelLayout.setVerticalGroup(
            MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MidProjectPanelLayout.createSequentialGroup()
                .addGroup(MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinimizeButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaximizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeMaximizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OnTakenPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OnGoingPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MemberBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProgressBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        RightProjectPanel.setBackground(new java.awt.Color(102, 204, 0));

        SearchIconR.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        SearchIconR.setText("search");
        SearchIconR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIconRActionPerformed(evt);
            }
        });

        SearchBarR.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        OnFinishPanel.setPreferredSize(new java.awt.Dimension(300, 450));

        MinimizeButtonR.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        MinimizeButtonR.setText("> >");
        MinimizeButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonRActionPerformed(evt);
            }
        });

        filterR.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        filterR.setText("filter");
        filterR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterRActionPerformed(evt);
            }
        });

        sortR.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        sortR.setText("sort");
        sortR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightProjectPanelLayout = new javax.swing.GroupLayout(RightProjectPanel);
        RightProjectPanel.setLayout(RightProjectPanelLayout);
        RightProjectPanelLayout.setHorizontalGroup(
            RightProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightProjectPanelLayout.createSequentialGroup()
                .addComponent(MinimizeButtonR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RightProjectPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(RightProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightProjectPanelLayout.createSequentialGroup()
                        .addGroup(RightProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SearchBarR, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sortR, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RightProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RightProjectPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(filterR, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RightProjectPanelLayout.createSequentialGroup()
                                .addComponent(SearchIconR, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(OnFinishPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        RightProjectPanelLayout.setVerticalGroup(
            RightProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightProjectPanelLayout.createSequentialGroup()
                .addComponent(MinimizeButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(RightProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBarR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchIconR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OnFinishPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RightProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterR))
                .addContainerGap())
        );

        DeMinimizeButtonR.setBackground(new java.awt.Color(153, 255, 51));
        DeMinimizeButtonR.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        DeMinimizeButtonR.setText("< >");
        DeMinimizeButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMinimizeButtonRActionPerformed(evt);
            }
        });

        DeMinimizeButtonL.setBackground(new java.awt.Color(0, 153, 204));
        DeMinimizeButtonL.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        DeMinimizeButtonL.setText("< >");
        DeMinimizeButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMinimizeButtonLActionPerformed(evt);
            }
        });

        DeMinimizeButtonM.setBackground(new java.awt.Color(255, 153, 51));
        DeMinimizeButtonM.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        DeMinimizeButtonM.setText("< >");
        DeMinimizeButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMinimizeButtonMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LeftProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13)
                        .addComponent(MidProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15)
                        .addComponent(RightProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DeMinimizeButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeMinimizeButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeMinimizeButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeMinimizeButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeMinimizeButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeMinimizeButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LeftProjectPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(MidProjectPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RightProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchIconLActionPerformed(java.awt.event.ActionEvent evt) {
        getBacklog().search(SearchBarL.getText());
    }

    private void SearchIconRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIconRActionPerformed
        getFinish().search(SearchBarR.getText());

    }//GEN-LAST:event_SearchIconRActionPerformed

    private void MaximizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaximizeButtonActionPerformed
        LeftProjectPanel.setVisible(false);
        RightProjectPanel.setVisible(false);
        MaximizeButton.setVisible(false);
        MinimizeButtonM.setVisible(false);
        DeMaximizeButton.setVisible(true);
        DeMinimizeButtonL.setVisible(true);
        DeMinimizeButtonR.setVisible(true);
    }//GEN-LAST:event_MaximizeButtonActionPerformed

    private void SortLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortLActionPerformed
        SortUI sortL = new SortUI(getBacklog());
        sortL.setVisible(true);
    }//GEN-LAST:event_SortLActionPerformed

    private void MinimizeButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonLActionPerformed
        LeftProjectPanel.setVisible(false);
        DeMinimizeButtonL.setVisible(true);
        MaximizeButton.setVisible(false);
    }//GEN-LAST:event_MinimizeButtonLActionPerformed

    private void sortRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortRActionPerformed
        SortUI sortR = new SortUI(getFinish());
        sortR.setVisible(true);
    }//GEN-LAST:event_sortRActionPerformed

    private void DeMinimizeButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMinimizeButtonLActionPerformed
        LeftProjectPanel.setVisible(true);
        DeMinimizeButtonL.setVisible(false);
        MaximizeButton.setVisible(true);
    }//GEN-LAST:event_DeMinimizeButtonLActionPerformed

    private void DeMinimizeButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMinimizeButtonMActionPerformed
        MidProjectPanel.setVisible(true);
        DeMinimizeButtonM.setVisible(false);
    }//GEN-LAST:event_DeMinimizeButtonMActionPerformed

    private void DeMinimizeButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMinimizeButtonRActionPerformed
        RightProjectPanel.setVisible(true);
        DeMinimizeButtonR.setVisible(false);
        MaximizeButton.setVisible(true);
    }//GEN-LAST:event_DeMinimizeButtonRActionPerformed

    private void DeMaximizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMaximizeButtonActionPerformed
        //TODO handle condition when maximize then deminimize both left and right and the demaximize still there
        LeftProjectPanel.setVisible(true);
        RightProjectPanel.setVisible(true);
        DeMaximizeButton.setVisible(false);
        MaximizeButton.setVisible(true);
        MinimizeButtonM.setVisible(true);
        DeMinimizeButtonL.setVisible(false);
        DeMinimizeButtonR.setVisible(false);
    }//GEN-LAST:event_DeMaximizeButtonActionPerformed

    private void MinimizeButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonMActionPerformed
        MidProjectPanel.setVisible(false);
        DeMinimizeButtonM.setVisible(true);
    }//GEN-LAST:event_MinimizeButtonMActionPerformed

    private void MinimizeButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonRActionPerformed
        RightProjectPanel.setVisible(false);
        DeMinimizeButtonR.setVisible(true);
        MaximizeButton.setVisible(false);
    }//GEN-LAST:event_MinimizeButtonRActionPerformed

    private void AddTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskButtonActionPerformed
        TaskCreate taskcreate = new TaskCreate(getBacklog());
        taskcreate.setVisible(true);
    }//GEN-LAST:event_AddTaskButtonActionPerformed

    private void FilterLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterLActionPerformed
        /*FilterUI filterL = new FilterUI(BoardType.BACKLOG);
        filterL.setVisible(true);*/
    }//GEN-LAST:event_FilterLActionPerformed

    private void filterRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterRActionPerformed
        /*FilterUI filterR = new FilterUI(BoardType.FINISH);
        filterR.setVisible(true);*/
    }//GEN-LAST:event_filterRActionPerformed

    private void ProgressBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgressBoardButtonActionPerformed
        ProgressBoard2 Pboard = new ProgressBoard2();
        Pboard.setVisible(true);

    }//GEN-LAST:event_ProgressBoardButtonActionPerformed

    private void MemberBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberBoardButtonActionPerformed
        TeamMemberBoard Mboard = new TeamMemberBoard();
        Mboard.setVisible(true);

    }//GEN-LAST:event_MemberBoardButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTaskButton;
    private javax.swing.JButton DeMaximizeButton;
    private javax.swing.JButton DeMinimizeButtonL;
    private javax.swing.JButton DeMinimizeButtonM;
    private javax.swing.JButton DeMinimizeButtonR;
    private javax.swing.JButton FilterL;
    private javax.swing.JPanel LeftProjectPanel;
    private javax.swing.JButton MaximizeButton;
    private javax.swing.JButton MemberBoardButton;
    private javax.swing.JPanel MidProjectPanel;
    private javax.swing.JButton MinimizeButtonL;
    private javax.swing.JButton MinimizeButtonM;
    private javax.swing.JButton MinimizeButtonR;
    private javax.swing.JScrollPane OnBacklogPanel;
    private javax.swing.JScrollPane OnFinishPanel;
    private javax.swing.JScrollPane OnGoingPanel;
    private javax.swing.JScrollPane OnTakenPanel;
    private javax.swing.JButton ProgressBoardButton;
    private javax.swing.JPanel RightProjectPanel;
    private javax.swing.JTextField SearchBarL;
    private javax.swing.JTextField SearchBarR;
    private javax.swing.JButton SearchIconL;
    private javax.swing.JButton SearchIconR;
    private javax.swing.JButton SortL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton filterR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton sortR;
    // End of variables declaration//GEN-END:variables

    public void setPMinimizeHidden() {
        DeMinimizeButtonL.setVisible(false);
        DeMinimizeButtonR.setVisible(false);
        DeMinimizeButtonM.setVisible(false);
        DeMaximizeButton.setVisible(false);
    }

    public void addTask() {
        addLog();
        OnBacklogPanel.setColumnHeaderView(null);
        OnTakenPanel.setColumnHeaderView(null);
        OnGoingPanel.setColumnHeaderView(null);
        OnFinishPanel.setColumnHeaderView(null);
        OnBacklogPanel.setViewportView(getBacklog());
        OnTakenPanel.setViewportView(getTaken());
        OnGoingPanel.setViewportView(getOngoing());
        OnFinishPanel.setViewportView(getFinish());
        if (getBacklog().getNumOfCardDisplay() == 0||getBacklog().getNumOfCardDisplay() == 1||getBacklog().getNumOfCardDisplay() == 2||getBacklog().getNumOfCardDisplay() == 3) {
            OnBacklogPanel.setViewportView(null);
            OnBacklogPanel.setColumnHeaderView(getBacklog());
        }
        if (getTaken().getNumOfCardDisplay() == 0||getTaken().getNumOfCardDisplay() == 1||getTaken().getNumOfCardDisplay() == 2||getTaken().getNumOfCardDisplay() == 3) {
            OnTakenPanel.setViewportView(null);
            OnTakenPanel.setColumnHeaderView(getTaken());
        }
        if (getOngoing().getNumOfCardDisplay() == 0||getOngoing().getNumOfCardDisplay() == 1||getOngoing().getNumOfCardDisplay() == 2||getOngoing().getNumOfCardDisplay() == 3) {
            OnGoingPanel.setViewportView(null);
            OnGoingPanel.setColumnHeaderView(getOngoing());
        }
        if (getFinish().getNumOfCardDisplay() == 0|getFinish().getNumOfCardDisplay() == 1||getFinish().getNumOfCardDisplay() == 2||getFinish().getNumOfCardDisplay() == 3) {
            OnFinishPanel.setViewportView(null);
            OnFinishPanel.setColumnHeaderView(getFinish());
        }

        if (CurrentUserhold.getUser() != null) {
            if (CurrentUserhold.getUser().getAccessRange() > 2) {
                MemberBoardButton.setVisible(true);
                ProgressBoardButton.setVisible(true);

            } else {
                MemberBoardButton.setVisible(false);
                ProgressBoardButton.setVisible(false);
            }

        }
    }

    public void refreshAllBoard() {
        getBacklog().refresh();
        getTaken().refresh();
        getOngoing().refresh();
        getFinish().refresh();
        OnBacklogPanel.setColumnHeaderView(null);
        OnTakenPanel.setColumnHeaderView(null);
        OnGoingPanel.setColumnHeaderView(null);
        OnFinishPanel.setColumnHeaderView(null);
        OnBacklogPanel.setViewportView(getBacklog());
        OnTakenPanel.setViewportView(getTaken());
        OnGoingPanel.setViewportView(getOngoing());
        OnFinishPanel.setViewportView(getFinish());
        
        if (getBacklog().getNumOfCardDisplay() == 0||getBacklog().getNumOfCardDisplay() == 1||getBacklog().getNumOfCardDisplay() == 2||getBacklog().getNumOfCardDisplay() == 3) {
            OnBacklogPanel.setViewportView(null);
            OnBacklogPanel.setColumnHeaderView(getBacklog());
        }
        if (getTaken().getNumOfCardDisplay() == 0||getTaken().getNumOfCardDisplay() == 1||getTaken().getNumOfCardDisplay() == 2||getTaken().getNumOfCardDisplay() == 3) {
            OnTakenPanel.setViewportView(null);
            OnTakenPanel.setColumnHeaderView(getTaken());
        }
        if (getOngoing().getNumOfCardDisplay() == 0||getOngoing().getNumOfCardDisplay() == 1||getOngoing().getNumOfCardDisplay() == 2||getOngoing().getNumOfCardDisplay() == 3) {
            OnGoingPanel.setViewportView(null);
            OnGoingPanel.setColumnHeaderView(getOngoing());
        }
        if (getFinish().getNumOfCardDisplay() == 0|getFinish().getNumOfCardDisplay() == 1||getFinish().getNumOfCardDisplay() == 2||getFinish().getNumOfCardDisplay() == 3) {
            OnFinishPanel.setViewportView(null);
            OnFinishPanel.setColumnHeaderView(getFinish());
        }

    }

    class componentChangeListener implements ContainerListener {

        @Override
        public void componentAdded(ContainerEvent arg0) {

        }

        @Override
        public void componentRemoved(ContainerEvent arg0) {
            LayoutUI.this.revalidate();
        }

    }

    /**
     * @return the backlog
     */
    public BoardUI getBacklog() {
        return backlog;
    }

    /**
     * @return the taken
     */
    public BoardUI getTaken() {
        return taken;
    }

    /**
     * @return the ongoing
     */
    public BoardUI getOngoing() {
        return ongoing;
    }

    /**
     * @return the finish
     */
    public BoardUI getFinish() {
        return finish;
    }
}
