/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout.views.layout;

import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;

import common.Comment.CommentsAllHold;
import layout.views.FilterUI.FilterUI;
import layout.views.SortUI.SortUI;
import common.Enum.BoardType;
import common.User.CurrentUserhold;
import layout.views.BoardUI.BoardUI;
import layout.views.TaskUI.TaskCreate;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author tug70
 */
public class LayoutUI extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * Creates new form Layout
     */
    public LayoutUI() {

        initComponents();
        setPMinimizeHidden();
        addTask();
    }
    private BoardUI backlog;
    private BoardUI taken;
    private BoardUI ongoing;
    private BoardUI finish;

    public void addLog(){
        
        backlog = new BoardUI(BoardType.BACKLOG);
        taken = new BoardUI(BoardType.TAKEN);
        ongoing = new BoardUI(BoardType.ONGOING);
        finish = new BoardUI(BoardType.FINISH);
        
        backlog.addContainerListener(new componentChangeListener());
        taken.addContainerListener(new componentChangeListener());
        ongoing.addContainerListener(new componentChangeListener());
        finish.addContainerListener(new componentChangeListener());
    }
    public void rerenderAllBoard(){
        //backlog.refresh();
        //taken.refresh();
        //ongoing.refresh();
        finish.refresh();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        LeftProjectPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OnBacklogPanel = new javax.swing.JScrollPane();
        SearchBarL = new javax.swing.JTextField();
        SearchIconL = new javax.swing.JButton();
        MinimizeButtonL = new javax.swing.JButton();
        SortL = new javax.swing.JButton();
        FilterL = new javax.swing.JButton();
        AddTaskButton = new javax.swing.JButton();
        MidProjectPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        OnTakenPanel = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        OnGoingPanel = new javax.swing.JScrollPane();
        MinimizeButtonM = new javax.swing.JButton();
        MaximizeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DeMaximizeButton = new javax.swing.JButton();
        RightProjectPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        OnFinishPanel = new javax.swing.JScrollPane();
        SearchIconR = new javax.swing.JButton();
        SearchBarR = new javax.swing.JTextField();
        MinimizeButtonR = new javax.swing.JButton();
        filterR = new javax.swing.JButton();
        sortR = new javax.swing.JButton();
        DeMinimizeButtonR = new javax.swing.JButton();
        DeMinimizeButtonL = new javax.swing.JButton();
        DeMinimizeButtonM = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1405, 675));

        LeftProjectPanel.setBackground(new java.awt.Color(0, 153, 204));

        jScrollPane1.setViewportView(OnBacklogPanel);

        SearchIconL.setText("search");
        SearchIconL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIconLActionPerformed(evt);
            }
        });

        MinimizeButtonL.setText("< <");
        MinimizeButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonLActionPerformed(evt);
            }
        });

        SortL.setText("sort");
        SortL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortLActionPerformed(evt);
            }
        });

        FilterL.setText("filter");
        FilterL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterLActionPerformed(evt);
            }
        });

        AddTaskButton.setText("add");
        AddTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftProjectPanelLayout = new javax.swing.GroupLayout(LeftProjectPanel);
        LeftProjectPanelLayout.setHorizontalGroup(
        	LeftProjectPanelLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(LeftProjectPanelLayout.createSequentialGroup()
        			.addGap(0, 405, Short.MAX_VALUE)
        			.addComponent(MinimizeButtonL))
        		.addGroup(LeftProjectPanelLayout.createSequentialGroup()
        			.addGap(30)
        			.addGroup(LeftProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(LeftProjectPanelLayout.createSequentialGroup()
        					.addComponent(SearchBarL, GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(SearchIconL, GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
        				.addGroup(LeftProjectPanelLayout.createSequentialGroup()
        					.addComponent(AddTaskButton, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
        					.addGap(92)
        					.addComponent(SortL, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
        					.addComponent(FilterL, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE))
        				.addGroup(LeftProjectPanelLayout.createSequentialGroup()
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 400, GroupLayout.PREFERRED_SIZE)
        					.addGap(0, 0, Short.MAX_VALUE)))
        			.addGap(30))
        );
        LeftProjectPanelLayout.setVerticalGroup(
        	LeftProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(LeftProjectPanelLayout.createSequentialGroup()
        			.addComponent(MinimizeButtonL, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(LeftProjectPanelLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(SearchBarL, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(SearchIconL))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 489, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
        			.addGroup(LeftProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(FilterL, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        				.addGroup(LeftProjectPanelLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(AddTaskButton, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        					.addComponent(SortL, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)))
        			.addGap(23))
        );
        LeftProjectPanel.setLayout(LeftProjectPanelLayout);

        MidProjectPanel.setBackground(new java.awt.Color(255, 204, 51));

        jScrollPane3.setViewportView(OnTakenPanel);

        jScrollPane5.setViewportView(OnGoingPanel);

        MinimizeButtonM.setText(">> <<");
        MinimizeButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonMActionPerformed(evt);
            }
        });

        MaximizeButton.setText("< >");
        MaximizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaximizeButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Ontaken");

        jLabel2.setText("Ongoing");

        DeMaximizeButton.setText("> <");
        DeMaximizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMaximizeButtonActionPerformed(evt);
            }
        });
        
        ProgressBoardButton = new JButton("PBoard\r\n");
        ProgressBoardButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		ProgressBoard2 Pboard = new ProgressBoard2();
        		Pboard.setVisible(true);
        	}
        });
        
        MemberBoardButton = new JButton("MBoard\r\n");
        MemberBoardButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		TeamMemberBoard Mboard = new TeamMemberBoard();
        		Mboard.setVisible(true);
        	}
        });
        
        
        	
      

        javax.swing.GroupLayout MidProjectPanelLayout = new javax.swing.GroupLayout(MidProjectPanel);
        MidProjectPanelLayout.setHorizontalGroup(
        	MidProjectPanelLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(MidProjectPanelLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(MidProjectPanelLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(MidProjectPanelLayout.createSequentialGroup()
        					.addGroup(MidProjectPanelLayout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabel1)
        						.addGroup(MidProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        							.addGroup(MidProjectPanelLayout.createSequentialGroup()
        								.addComponent(ProgressBoardButton)
        								.addGap(18)
        								.addComponent(MemberBoardButton))
        							.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 400, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addGroup(MidProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 400, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel2)))
        				.addGroup(MidProjectPanelLayout.createSequentialGroup()
        					.addComponent(MaximizeButton)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(DeMaximizeButton)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(MinimizeButtonM)
        					.addGap(1)))
        			.addContainerGap())
        );
        MidProjectPanelLayout.setVerticalGroup(
        	MidProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(MidProjectPanelLayout.createSequentialGroup()
        			.addGroup(MidProjectPanelLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(MinimizeButtonM, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(MaximizeButton, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(DeMaximizeButton, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
        			.addGap(8)
        			.addGroup(MidProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel2, Alignment.TRAILING)
        				.addComponent(jLabel1))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(MidProjectPanelLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 489, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 489, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(MidProjectPanelLayout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(MemberBoardButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(ProgressBoardButton, GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        			.addGap(21))
        );
        MidProjectPanel.setLayout(MidProjectPanelLayout);

        RightProjectPanel.setBackground(new java.awt.Color(102, 204, 0));

        jScrollPane7.setViewportView(OnFinishPanel);

        SearchIconR.setText("search");
        SearchIconR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIconRActionPerformed(evt);
            }
        });

        MinimizeButtonR.setText("> >");
        MinimizeButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonRActionPerformed(evt);
            }
        });

        filterR.setText("filter");
        filterR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterRActionPerformed(evt);
            }
        });

        sortR.setText("sort");
        sortR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightProjectPanelLayout = new javax.swing.GroupLayout(RightProjectPanel);
        RightProjectPanelLayout.setHorizontalGroup(
        	RightProjectPanelLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(RightProjectPanelLayout.createSequentialGroup()
        			.addComponent(MinimizeButtonR)
        			.addContainerGap(405, Short.MAX_VALUE))
        		.addGroup(RightProjectPanelLayout.createSequentialGroup()
        			.addGap(30)
        			.addGroup(RightProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(RightProjectPanelLayout.createSequentialGroup()
        					.addGroup(RightProjectPanelLayout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(RightProjectPanelLayout.createSequentialGroup()
        							.addComponent(SearchBarR, GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(SearchIconR, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        						.addComponent(jScrollPane7, GroupLayout.PREFERRED_SIZE, 400, GroupLayout.PREFERRED_SIZE))
        					.addGap(30))
        				.addGroup(RightProjectPanelLayout.createSequentialGroup()
        					.addGap(47)
        					.addComponent(sortR, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
        					.addGap(161)
        					.addComponent(filterR, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap(86, Short.MAX_VALUE))))
        );
        RightProjectPanelLayout.setVerticalGroup(
        	RightProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(RightProjectPanelLayout.createSequentialGroup()
        			.addComponent(MinimizeButtonR, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        			.addGap(11)
        			.addGroup(RightProjectPanelLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(SearchBarR, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(SearchIconR))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane7, GroupLayout.PREFERRED_SIZE, 489, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(RightProjectPanelLayout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(filterR, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        				.addComponent(sortR, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
        			.addGap(15))
        );
        RightProjectPanel.setLayout(RightProjectPanelLayout);

        DeMinimizeButtonR.setBackground(new java.awt.Color(153, 255, 51));
        DeMinimizeButtonR.setText("< >");
        DeMinimizeButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMinimizeButtonRActionPerformed(evt);
            }
        });

        DeMinimizeButtonL.setBackground(new java.awt.Color(0, 153, 204));
        DeMinimizeButtonL.setText("< >");
        DeMinimizeButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMinimizeButtonLActionPerformed(evt);
            }
        });

        DeMinimizeButtonM.setBackground(new java.awt.Color(255, 153, 51));
        DeMinimizeButtonM.setText("< >");
        DeMinimizeButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMinimizeButtonMActionPerformed(evt);
            }
        });
        GroupLayout groupLayout = new GroupLayout(this);
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(179)
        			.addComponent(DeMinimizeButtonL, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
        			.addGap(595)
        			.addComponent(DeMinimizeButtonM, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
        			.addGap(609)
        			.addComponent(DeMinimizeButtonR, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(20)
        			.addComponent(LeftProjectPanel, GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        			.addGap(12)
        			.addComponent(MidProjectPanel, GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        			.addGap(12)
        			.addComponent(RightProjectPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(10)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(DeMinimizeButtonL, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(DeMinimizeButtonM, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(DeMinimizeButtonR, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(LeftProjectPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(2)
        					.addComponent(MidProjectPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(2)
        					.addComponent(RightProjectPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        			.addGap(10))
        );
        setLayout(groupLayout);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchIconLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIconLActionPerformed\
        backlog.search(SearchBarL.getText());
    }//GEN-LAST:event_SearchIconLActionPerformed

    private void SearchIconRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIconRActionPerformed
    	finish.search(SearchBarR.getText());

    }//GEN-LAST:event_SearchIconRActionPerformed

    private void MaximizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaximizeButtonActionPerformed
        LeftProjectPanel.setVisible(false);
        RightProjectPanel.setVisible(false);
        MaximizeButton.setVisible(false);
        MinimizeButtonM.setVisible(false);
        DeMaximizeButton.setVisible(true);
        DeMinimizeButtonL.setVisible(true);
        DeMinimizeButtonR.setVisible(true);
    }//GEN-LAST:event_MaximizeButtonActionPerformed

    private void SortLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortLActionPerformed
        SortUI sortL = new SortUI(backlog);
        sortL.setVisible(true);
    }//GEN-LAST:event_SortLActionPerformed

    private void MinimizeButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonLActionPerformed
        LeftProjectPanel.setVisible(false);
        DeMinimizeButtonL.setVisible(true);
        MaximizeButton.setVisible(false);
    }//GEN-LAST:event_MinimizeButtonLActionPerformed

    private void sortRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortRActionPerformed
        SortUI sortR = new SortUI(finish);
        sortR.setVisible(true);
    }//GEN-LAST:event_sortRActionPerformed

    private void DeMinimizeButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMinimizeButtonLActionPerformed
        LeftProjectPanel.setVisible(true);
        DeMinimizeButtonL.setVisible(false);
        MaximizeButton.setVisible(true);
    }//GEN-LAST:event_DeMinimizeButtonLActionPerformed

    private void DeMinimizeButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMinimizeButtonMActionPerformed
        MidProjectPanel.setVisible(true);
        DeMinimizeButtonM.setVisible(false);
    }//GEN-LAST:event_DeMinimizeButtonMActionPerformed

    private void DeMinimizeButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMinimizeButtonRActionPerformed
        RightProjectPanel.setVisible(true);
        DeMinimizeButtonR.setVisible(false);
        MaximizeButton.setVisible(true);
    }//GEN-LAST:event_DeMinimizeButtonRActionPerformed

    private void DeMaximizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMaximizeButtonActionPerformed
        //TODO handle condition when maximize then deminimize both left and right and the demaximize still there
        LeftProjectPanel.setVisible(true);
        RightProjectPanel.setVisible(true);
        DeMaximizeButton.setVisible(false);
        MaximizeButton.setVisible(true);
        MinimizeButtonM.setVisible(true);
        DeMinimizeButtonL.setVisible(false);
        DeMinimizeButtonR.setVisible(false);
    }//GEN-LAST:event_DeMaximizeButtonActionPerformed

    private void MinimizeButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonMActionPerformed
        MidProjectPanel.setVisible(false);
        DeMinimizeButtonM.setVisible(true);
    }//GEN-LAST:event_MinimizeButtonMActionPerformed

    private void MinimizeButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonRActionPerformed
        RightProjectPanel.setVisible(false);
        DeMinimizeButtonR.setVisible(true);
        MaximizeButton.setVisible(false);
    }//GEN-LAST:event_MinimizeButtonRActionPerformed

    private void AddTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskButtonActionPerformed
        TaskCreate taskcreate = new TaskCreate(backlog);
        taskcreate.setVisible(true);
    }//GEN-LAST:event_AddTaskButtonActionPerformed

    private void FilterLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterLActionPerformed
        FilterUI filterL = new FilterUI();
        filterL.setVisible(true);
        /*filterL.FilterButton.addActionListener(new ActionListener() {
					public void actionPerformed(ActionEvent e) {
						if (filterL.FilterOption1.isSelected()) {
							total = total - 5;
						} 
						
						if (filterL.FilterOption2.isSelected()) {
							total = total - 10;
						} 
						
						if (filterL.FilterOption3.isSelected()) {
							total = total - 15;
						} 
						
						if (filterL.FilterOption4.isSelected()) {
							total = total - 20;
						} 	
						
						testFilterText.setText(Double.toString(total));
						filterL.dispose();
					}
				});*/
    }//GEN-LAST:event_FilterLActionPerformed

    private void filterRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterRActionPerformed
        FilterUI filterR = new FilterUI();
        filterR.setVisible(true);
        /*filterL.FilterButton.addActionListener(new ActionListener() {
					public void actionPerformed(ActionEvent e) {
						if (filterL.FilterOption1.isSelected()) {
							total = total - 5;
						} 
						
						if (filterL.FilterOption2.isSelected()) {
							total = total - 10;
						} 
						
						if (filterL.FilterOption3.isSelected()) {
							total = total - 15;
						} 
						
						if (filterL.FilterOption4.isSelected()) {
							total = total - 20;
						} 	
						
						testFilterText.setText(Double.toString(total));
						filterL.dispose();
					}
				});*/
    }//GEN-LAST:event_filterRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTaskButton;
    private javax.swing.JButton DeMaximizeButton;
    private javax.swing.JButton DeMinimizeButtonL;
    private javax.swing.JButton DeMinimizeButtonM;
    private javax.swing.JButton DeMinimizeButtonR;
    private javax.swing.JButton FilterL;
    private javax.swing.JPanel LeftProjectPanel;
    private javax.swing.JButton MaximizeButton;
    private javax.swing.JPanel MidProjectPanel;
    private javax.swing.JButton MinimizeButtonL;
    private javax.swing.JButton MinimizeButtonM;
    private javax.swing.JButton MinimizeButtonR;
    private javax.swing.JScrollPane OnBacklogPanel;
    private javax.swing.JScrollPane OnFinishPanel;
    private javax.swing.JScrollPane OnGoingPanel;
    private javax.swing.JScrollPane OnTakenPanel;
    private javax.swing.JPanel RightProjectPanel;
    private javax.swing.JTextField SearchBarL;
    private javax.swing.JTextField SearchBarR;
    private javax.swing.JButton SearchIconL;
    private javax.swing.JButton SearchIconR;
    private javax.swing.JButton SortL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton filterR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton sortR;
    private JButton ProgressBoardButton;
    private JButton MemberBoardButton;
    // End of variables declaration//GEN-END:variables
    

    public void setPMinimizeHidden() {
        DeMinimizeButtonL.setVisible(false);
        DeMinimizeButtonR.setVisible(false);
        DeMinimizeButtonM.setVisible(false);
        DeMaximizeButton.setVisible(false);
    }
    public void addTask() {
        addLog();
        OnBacklogPanel.setViewportView(backlog);
        OnTakenPanel.setViewportView(taken);
        OnGoingPanel.setViewportView(ongoing);
        OnFinishPanel.setViewportView(finish);
        
        if (CurrentUserhold.getUser()!=null) {
        	if (CurrentUserhold.getUser().getAccessRange()>2) {
        		MemberBoardButton.setVisible(true);
        		ProgressBoardButton.setVisible(true);
        
        	} else {
        		MemberBoardButton.setVisible(false);
        		ProgressBoardButton.setVisible(false);
        	}
		
	}
    }
    public void refreshAllBoard(){
        backlog.refresh();
        taken.refresh();
        ongoing.refresh();
        finish.refresh();
        OnBacklogPanel.setViewportView(backlog);
        OnTakenPanel.setViewportView(taken);
        OnGoingPanel.setViewportView(ongoing);
        OnFinishPanel.setViewportView(finish);
    }
    
    class componentChangeListener implements ContainerListener {

    	@Override
    	public void componentAdded(ContainerEvent arg0) {
    		
    	}

    	@Override
    	public void componentRemoved(ContainerEvent arg0) {
    		LayoutUI.this.revalidate();
    	}
    	
    }
}
