/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import TrungAndAnhIntegration.common.Enum.BoardType;
import TrungAndAnhIntegration.common.TaskHold.TaskHold;
import TrungAndAnhIntegration.layout.views.BoardUI.BoardUI;
import TrungAndAnhIntegration.layout.views.TaskCreate;
import task.TaskCreateUpdateUI;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author tug70
 */
public class LayoutUI extends javax.swing.JPanel {

    /**
     * Creates new form Layout
     */
    public LayoutUI() {

        initComponents();
        setPMinimizeHidden();
        renderBoard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        LeftProjectPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OnBacklogPanel = new javax.swing.JScrollPane();
        SearchBarL = new javax.swing.JTextField();
        SearchIconL = new javax.swing.JButton();
        MinimizeButtonL = new javax.swing.JButton();
        SortL = new javax.swing.JButton();
        FilterL = new javax.swing.JButton();
        AddTaskButton = new javax.swing.JButton();
        MidProjectPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        OnTakenPanel = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        OnGoingPanel = new javax.swing.JScrollPane();
        MinimizeButtonM = new javax.swing.JButton();
        MaximizeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DeMaximizeButton = new javax.swing.JButton();
        RightProjectPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        OnFinishPanel = new javax.swing.JScrollPane();
        SearchIconR = new javax.swing.JButton();
        SearchBarR = new javax.swing.JTextField();
        MinimizeButtonR = new javax.swing.JButton();
        filterR = new javax.swing.JButton();
        sortR = new javax.swing.JButton();
        DeMinimizeButtonR = new javax.swing.JButton();
        DeMinimizeButtonL = new javax.swing.JButton();
        DeMinimizeButtonM = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1405, 675));

        LeftProjectPanel.setBackground(new java.awt.Color(0, 153, 204));

        jScrollPane1.setViewportView(OnBacklogPanel);

        SearchIconL.setText("search");
        SearchIconL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIconLActionPerformed(evt);
            }
        });

        MinimizeButtonL.setText("< <");
        MinimizeButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonLActionPerformed(evt);
            }
        });

        SortL.setText("sort");
        SortL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortLActionPerformed(evt);
            }
        });

        FilterL.setText("filter");
        FilterL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterLActionPerformed(evt);
            }
        });

        AddTaskButton.setText("add");
        AddTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftProjectPanelLayout = new javax.swing.GroupLayout(LeftProjectPanel);
        LeftProjectPanel.setLayout(LeftProjectPanelLayout);
        LeftProjectPanelLayout.setHorizontalGroup(
            LeftProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftProjectPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MinimizeButtonL))
            .addGroup(LeftProjectPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(LeftProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftProjectPanelLayout.createSequentialGroup()
                        .addComponent(SearchBarL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchIconL, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LeftProjectPanelLayout.createSequentialGroup()
                        .addComponent(AddTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(SortL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FilterL, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LeftProjectPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        LeftProjectPanelLayout.setVerticalGroup(
            LeftProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftProjectPanelLayout.createSequentialGroup()
                .addComponent(MinimizeButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LeftProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBarL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchIconL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LeftProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FilterL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LeftProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SortL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        MidProjectPanel.setBackground(new java.awt.Color(255, 204, 51));

        jScrollPane3.setViewportView(OnTakenPanel);

        jScrollPane5.setViewportView(OnGoingPanel);

        MinimizeButtonM.setText(">> <<");
        MinimizeButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonMActionPerformed(evt);
            }
        });

        MaximizeButton.setText("< >");
        MaximizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaximizeButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Ontaken");

        jLabel2.setText("Ongoing");

        DeMaximizeButton.setText("> <");
        DeMaximizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMaximizeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MidProjectPanelLayout = new javax.swing.GroupLayout(MidProjectPanel);
        MidProjectPanel.setLayout(MidProjectPanelLayout);
        MidProjectPanelLayout.setHorizontalGroup(
            MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MidProjectPanelLayout.createSequentialGroup()
                .addGroup(MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MidProjectPanelLayout.createSequentialGroup()
                        .addContainerGap(40, Short.MAX_VALUE)
                        .addGroup(MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(MidProjectPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MaximizeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeMaximizeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinimizeButtonM)
                        .addGap(1, 1, 1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        MidProjectPanelLayout.setVerticalGroup(
            MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MidProjectPanelLayout.createSequentialGroup()
                .addGroup(MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinimizeButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaximizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeMaximizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MidProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        RightProjectPanel.setBackground(new java.awt.Color(102, 204, 0));

        jScrollPane7.setViewportView(OnFinishPanel);

        SearchIconR.setText("search");
        SearchIconR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIconRActionPerformed(evt);
            }
        });

        MinimizeButtonR.setText("> >");
        MinimizeButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonRActionPerformed(evt);
            }
        });

        filterR.setText("filter");
        filterR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterRActionPerformed(evt);
            }
        });

        sortR.setText("sort");
        sortR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightProjectPanelLayout = new javax.swing.GroupLayout(RightProjectPanel);
        RightProjectPanel.setLayout(RightProjectPanelLayout);
        RightProjectPanelLayout.setHorizontalGroup(
            RightProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightProjectPanelLayout.createSequentialGroup()
                .addComponent(MinimizeButtonR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightProjectPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(RightProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(RightProjectPanelLayout.createSequentialGroup()
                        .addGroup(RightProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(RightProjectPanelLayout.createSequentialGroup()
                                .addComponent(SearchBarR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchIconR, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(RightProjectPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(sortR, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filterR, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))))
        );
        RightProjectPanelLayout.setVerticalGroup(
            RightProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightProjectPanelLayout.createSequentialGroup()
                .addComponent(MinimizeButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(RightProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBarR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchIconR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RightProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sortR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        DeMinimizeButtonR.setBackground(new java.awt.Color(153, 255, 51));
        DeMinimizeButtonR.setText("< >");
        DeMinimizeButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMinimizeButtonRActionPerformed(evt);
            }
        });

        DeMinimizeButtonL.setBackground(new java.awt.Color(0, 153, 204));
        DeMinimizeButtonL.setText("< >");
        DeMinimizeButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMinimizeButtonLActionPerformed(evt);
            }
        });

        DeMinimizeButtonM.setBackground(new java.awt.Color(255, 153, 51));
        DeMinimizeButtonM.setText("< >");
        DeMinimizeButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMinimizeButtonMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LeftProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MidProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RightProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(DeMinimizeButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(595, 595, 595)
                .addComponent(DeMinimizeButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeMinimizeButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeMinimizeButtonL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeMinimizeButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DeMinimizeButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LeftProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MidProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RightProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchIconLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIconLActionPerformed
        TaskCreateUpdateUI taskcreate = new TaskCreateUpdateUI();
        taskcreate.setVisible(true);
    }//GEN-LAST:event_SearchIconLActionPerformed

    private void SearchIconRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIconRActionPerformed
        TaskCreateUpdateUI taskcreate = new TaskCreateUpdateUI();
        taskcreate.setVisible(true);
    }//GEN-LAST:event_SearchIconRActionPerformed

    private void MaximizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaximizeButtonActionPerformed
        LeftProjectPanel.setVisible(false);
        RightProjectPanel.setVisible(false);
        MaximizeButton.setVisible(false);
        MinimizeButtonM.setVisible(false);
        DeMaximizeButton.setVisible(true);
        DeMinimizeButtonL.setVisible(true);
        DeMinimizeButtonR.setVisible(true);
    }//GEN-LAST:event_MaximizeButtonActionPerformed

    private void SortLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortLActionPerformed
        SortUI sortL = new SortUI();
        sortL.setVisible(true);
    }//GEN-LAST:event_SortLActionPerformed

    private void MinimizeButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonLActionPerformed
        LeftProjectPanel.setVisible(false);
        DeMinimizeButtonL.setVisible(true);
        MaximizeButton.setVisible(false);
    }//GEN-LAST:event_MinimizeButtonLActionPerformed

    private void sortRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortRActionPerformed
        SortUI sortR = new SortUI();
        sortR.setVisible(true);
    }//GEN-LAST:event_sortRActionPerformed

    private void DeMinimizeButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMinimizeButtonLActionPerformed
        LeftProjectPanel.setVisible(true);
        DeMinimizeButtonL.setVisible(false);
        MaximizeButton.setVisible(true);
    }//GEN-LAST:event_DeMinimizeButtonLActionPerformed

    private void DeMinimizeButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMinimizeButtonMActionPerformed
        MidProjectPanel.setVisible(true);
        DeMinimizeButtonM.setVisible(false);
    }//GEN-LAST:event_DeMinimizeButtonMActionPerformed

    private void DeMinimizeButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMinimizeButtonRActionPerformed
        RightProjectPanel.setVisible(true);
        DeMinimizeButtonR.setVisible(false);
        MaximizeButton.setVisible(true);
    }//GEN-LAST:event_DeMinimizeButtonRActionPerformed

    private void DeMaximizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMaximizeButtonActionPerformed
        //TODO handle condition when maximize then deminimize both left and right and the demaximize still there
        LeftProjectPanel.setVisible(true);
        RightProjectPanel.setVisible(true);
        DeMaximizeButton.setVisible(false);
        MaximizeButton.setVisible(true);
        MinimizeButtonM.setVisible(true);
        DeMinimizeButtonL.setVisible(false);
        DeMinimizeButtonR.setVisible(false);
    }//GEN-LAST:event_DeMaximizeButtonActionPerformed

    private void MinimizeButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonMActionPerformed
        MidProjectPanel.setVisible(false);
        DeMinimizeButtonM.setVisible(true);
    }//GEN-LAST:event_MinimizeButtonMActionPerformed

    private void MinimizeButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonRActionPerformed
        RightProjectPanel.setVisible(false);
        DeMinimizeButtonR.setVisible(true);
        MaximizeButton.setVisible(false);
    }//GEN-LAST:event_MinimizeButtonRActionPerformed

    private void AddTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskButtonActionPerformed
        TaskCreate taskcreate = new TaskCreate();
        taskcreate.setVisible(true);
    }//GEN-LAST:event_AddTaskButtonActionPerformed

    private void FilterLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterLActionPerformed
        FilterUI filterL = new FilterUI();
        filterL.setVisible(true);
        /*filterL.FilterButton.addActionListener(new ActionListener() {
					public void actionPerformed(ActionEvent e) {
						if (filterL.FilterOption1.isSelected()) {
							total = total - 5;
						} 
						
						if (filterL.FilterOption2.isSelected()) {
							total = total - 10;
						} 
						
						if (filterL.FilterOption3.isSelected()) {
							total = total - 15;
						} 
						
						if (filterL.FilterOption4.isSelected()) {
							total = total - 20;
						} 	
						
						testFilterText.setText(Double.toString(total));
						filterL.dispose();
					}
				});*/
    }//GEN-LAST:event_FilterLActionPerformed

    private void filterRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterRActionPerformed
        FilterUI filterR = new FilterUI();
        filterR.setVisible(true);
        /*filterL.FilterButton.addActionListener(new ActionListener() {
					public void actionPerformed(ActionEvent e) {
						if (filterL.FilterOption1.isSelected()) {
							total = total - 5;
						} 
						
						if (filterL.FilterOption2.isSelected()) {
							total = total - 10;
						} 
						
						if (filterL.FilterOption3.isSelected()) {
							total = total - 15;
						} 
						
						if (filterL.FilterOption4.isSelected()) {
							total = total - 20;
						} 	
						
						testFilterText.setText(Double.toString(total));
						filterL.dispose();
					}
				});*/
    }//GEN-LAST:event_filterRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTaskButton;
    private javax.swing.JButton DeMaximizeButton;
    private javax.swing.JButton DeMinimizeButtonL;
    private javax.swing.JButton DeMinimizeButtonM;
    private javax.swing.JButton DeMinimizeButtonR;
    private javax.swing.JButton FilterL;
    private javax.swing.JPanel LeftProjectPanel;
    private javax.swing.JButton MaximizeButton;
    private javax.swing.JPanel MidProjectPanel;
    private javax.swing.JButton MinimizeButtonL;
    private javax.swing.JButton MinimizeButtonM;
    private javax.swing.JButton MinimizeButtonR;
    private static javax.swing.JScrollPane OnBacklogPanel;
    private static javax.swing.JScrollPane OnFinishPanel;
    private static javax.swing.JScrollPane OnGoingPanel;
    private static javax.swing.JScrollPane OnTakenPanel;
    private javax.swing.JPanel RightProjectPanel;
    private javax.swing.JTextField SearchBarL;
    private javax.swing.JTextField SearchBarR;
    private javax.swing.JButton SearchIconL;
    private javax.swing.JButton SearchIconR;
    private javax.swing.JButton SortL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton filterR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton sortR;
    // End of variables declaration//GEN-END:variables
    private static BoardUI backlog;
    private static BoardUI taken;
    private static BoardUI ongoing;
    private static BoardUI finish;

    public void setPMinimizeHidden() {
        DeMinimizeButtonL.setVisible(false);
        DeMinimizeButtonR.setVisible(false);
        DeMinimizeButtonM.setVisible(false);
        DeMaximizeButton.setVisible(false);
    }

    public static void addTaskToBoards() {
        TaskHold.loadTask();
        backlog = new BoardUI(BoardType.BACKLOG);
        taken = new BoardUI(BoardType.TAKEN);
        ongoing = new BoardUI(BoardType.ONGOING);
        finish = new BoardUI(BoardType.FINISH);

        
    }
    public static void renderBoard(){
        addTaskToBoards();
        OnBacklogPanel.setViewportView(backlog);
        OnTakenPanel.setViewportView(taken);
        OnGoingPanel.setViewportView(ongoing);
        OnFinishPanel.setViewportView(finish);
    }
}
