/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import TrungAndAnhIntegration.common.Enum.BoardType;
import TrungAndAnhIntegration.common.TaskHold.TaskHold;
import TrungAndAnhIntegration.layout.views.BoardUI.BoardUI;
import TrungAndAnhIntegration.layout.views.TaskCreate;
import task.TaskCreateUpdateUI;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author tug70
 */
public class LayoutUI extends javax.swing.JPanel {

    /**
     * Creates new form Layout
     */
    public LayoutUI() {

        initComponents();
        setPMinimizeHidden();
        addTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        LeftProjectPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OnBacklogPanel = new javax.swing.JScrollPane();
        SearchBarL = new javax.swing.JTextField();
        SearchIconL = new javax.swing.JButton();
        MinimizeButtonL = new javax.swing.JButton();
        SortL = new javax.swing.JButton();
        FilterL = new javax.swing.JButton();
        AddTaskButton = new javax.swing.JButton();
        MidProjectPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        OnTakenPanel = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        OnGoingPanel = new javax.swing.JScrollPane();
        MinimizeButtonM = new javax.swing.JButton();
        MaximizeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DeMaximizeButton = new javax.swing.JButton();
        RightProjectPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        OnFinishPanel = new javax.swing.JScrollPane();
        SearchIconR = new javax.swing.JButton();
        SearchBarR = new javax.swing.JTextField();
        MinimizeButtonR = new javax.swing.JButton();
        filterR = new javax.swing.JButton();
        sortR = new javax.swing.JButton();
        DeMinimizeButtonR = new javax.swing.JButton();
        DeMinimizeButtonL = new javax.swing.JButton();
        DeMinimizeButtonM = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1405, 675));

        LeftProjectPanel.setBackground(new java.awt.Color(0, 153, 204));

        jScrollPane1.setViewportView(OnBacklogPanel);

        SearchIconL.setText("search");
        SearchIconL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIconLActionPerformed(evt);
            }
        });

        MinimizeButtonL.setText("< <");
        MinimizeButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonLActionPerformed(evt);
            }
        });

        SortL.setText("sort");
        SortL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortLActionPerformed(evt);
            }
        });

        FilterL.setText("filter");
        FilterL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterLActionPerformed(evt);
            }
        });

        AddTaskButton.setText("add");
        AddTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftProjectPanelLayout = new javax.swing.GroupLayout(LeftProjectPanel);
        LeftProjectPanelLayout.setHorizontalGroup(
        	LeftProjectPanelLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(LeftProjectPanelLayout.createSequentialGroup()
        			.addGap(0, 292, Short.MAX_VALUE)
        			.addComponent(MinimizeButtonL))
        		.addGroup(LeftProjectPanelLayout.createSequentialGroup()
        			.addGap(20)
        			.addGroup(LeftProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(LeftProjectPanelLayout.createSequentialGroup()
        					.addComponent(SearchBarL, GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(SearchIconL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addGroup(LeftProjectPanelLayout.createSequentialGroup()
        					.addComponent(AddTaskButton, GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        					.addGap(50)
        					.addComponent(SortL, GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        					.addGap(49)
        					.addComponent(FilterL, GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
        				.addGroup(LeftProjectPanelLayout.createSequentialGroup()
        					.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        					.addGap(0)))
        			.addGap(20))
        );
        LeftProjectPanelLayout.setVerticalGroup(
        	LeftProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(LeftProjectPanelLayout.createSequentialGroup()
        			.addComponent(MinimizeButtonL, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(LeftProjectPanelLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(SearchBarL, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(SearchIconL))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        			.addGap(18)
        			.addGroup(LeftProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(FilterL, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        				.addGroup(LeftProjectPanelLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(AddTaskButton, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        					.addComponent(SortL, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)))
        			.addGap(23))
        );
        LeftProjectPanel.setLayout(LeftProjectPanelLayout);

        MidProjectPanel.setBackground(new java.awt.Color(255, 204, 51));

        jScrollPane3.setViewportView(OnTakenPanel);

        jScrollPane5.setViewportView(OnGoingPanel);

        MinimizeButtonM.setText(">> <<");
        MinimizeButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonMActionPerformed(evt);
            }
        });

        MaximizeButton.setText("< >");
        MaximizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaximizeButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Ontaken");

        jLabel2.setText("Ongoing");

        DeMaximizeButton.setText("> <");
        DeMaximizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMaximizeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MidProjectPanelLayout = new javax.swing.GroupLayout(MidProjectPanel);
        MidProjectPanelLayout.setHorizontalGroup(
        	MidProjectPanelLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(MidProjectPanelLayout.createSequentialGroup()
        			.addGroup(MidProjectPanelLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(MidProjectPanelLayout.createSequentialGroup()
        					.addGap(33)
        					.addGroup(MidProjectPanelLayout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(MidProjectPanelLayout.createSequentialGroup()
        							.addGap(353)
        							.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        						.addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        					.addGap(12)
        					.addGroup(MidProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jScrollPane5, GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        						.addGroup(MidProjectPanelLayout.createSequentialGroup()
        							.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addGap(353))))
        				.addGroup(MidProjectPanelLayout.createSequentialGroup()
        					.addContainerGap(660, Short.MAX_VALUE)
        					.addComponent(MaximizeButton)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(DeMaximizeButton)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(MinimizeButtonM)
        					.addGap(1)))
        			.addGap(28))
        );
        MidProjectPanelLayout.setVerticalGroup(
        	MidProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(MidProjectPanelLayout.createSequentialGroup()
        			.addGroup(MidProjectPanelLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(MinimizeButtonM, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(MaximizeButton, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(DeMaximizeButton, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
        			.addGap(8)
        			.addGroup(MidProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel2, Alignment.TRAILING)
        				.addComponent(jLabel1))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(MidProjectPanelLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jScrollPane5, GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        				.addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
        			.addGap(79))
        );
        MidProjectPanel.setLayout(MidProjectPanelLayout);

        RightProjectPanel.setBackground(new java.awt.Color(102, 204, 0));

        jScrollPane7.setViewportView(OnFinishPanel);

        SearchIconR.setText("search");
        SearchIconR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIconRActionPerformed(evt);
            }
        });

        MinimizeButtonR.setText("> >");
        MinimizeButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonRActionPerformed(evt);
            }
        });

        filterR.setText("filter");
        filterR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterRActionPerformed(evt);
            }
        });

        sortR.setText("sort");
        sortR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightProjectPanelLayout = new javax.swing.GroupLayout(RightProjectPanel);
        RightProjectPanelLayout.setHorizontalGroup(
        	RightProjectPanelLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(RightProjectPanelLayout.createSequentialGroup()
        			.addComponent(MinimizeButtonR)
        			.addContainerGap(405, Short.MAX_VALUE))
        		.addGroup(RightProjectPanelLayout.createSequentialGroup()
        			.addGap(30)
        			.addGroup(RightProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(RightProjectPanelLayout.createSequentialGroup()
        					.addGroup(RightProjectPanelLayout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(RightProjectPanelLayout.createSequentialGroup()
        							.addComponent(SearchBarR)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(SearchIconR, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        						.addComponent(jScrollPane7, GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        					.addGap(30))
        				.addGroup(RightProjectPanelLayout.createSequentialGroup()
        					.addGap(47)
        					.addComponent(sortR, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(filterR, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
        					.addGap(86))))
        );
        RightProjectPanelLayout.setVerticalGroup(
        	RightProjectPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(RightProjectPanelLayout.createSequentialGroup()
        			.addComponent(MinimizeButtonR, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        			.addGap(11)
        			.addGroup(RightProjectPanelLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(SearchBarR, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(SearchIconR))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane7, GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        			.addGap(18)
        			.addGroup(RightProjectPanelLayout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(filterR, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        				.addComponent(sortR, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
        			.addGap(15))
        );
        RightProjectPanel.setLayout(RightProjectPanelLayout);

        DeMinimizeButtonR.setBackground(new java.awt.Color(153, 255, 51));
        DeMinimizeButtonR.setText("< >");
        DeMinimizeButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMinimizeButtonRActionPerformed(evt);
            }
        });

        DeMinimizeButtonL.setBackground(new java.awt.Color(0, 153, 204));
        DeMinimizeButtonL.setText("< >");
        DeMinimizeButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMinimizeButtonLActionPerformed(evt);
            }
        });

        DeMinimizeButtonM.setBackground(new java.awt.Color(255, 153, 51));
        DeMinimizeButtonM.setText("< >");
        DeMinimizeButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeMinimizeButtonMActionPerformed(evt);
            }
        });
        GroupLayout groupLayout = new GroupLayout(this);
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(107)
        			.addComponent(DeMinimizeButtonL, GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        			.addGap(561)
        			.addComponent(DeMinimizeButtonM, GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        			.addGap(676)
        			.addComponent(DeMinimizeButtonR, GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        			.addGap(12))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(12)
        			.addComponent(LeftProjectPanel, GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        			.addGap(7)
        			.addComponent(MidProjectPanel, GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
        			.addGap(7)
        			.addComponent(RightProjectPanel, GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(DeMinimizeButtonL, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        					.addComponent(DeMinimizeButtonM, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
        				.addComponent(DeMinimizeButtonR, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(LeftProjectPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(2)
        					.addComponent(MidProjectPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(2)
        					.addComponent(RightProjectPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        			.addGap(0))
        );
        setLayout(groupLayout);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchIconLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIconLActionPerformed
        TaskCreateUpdateUI taskcreate = new TaskCreateUpdateUI();
        taskcreate.setVisible(true);
    }//GEN-LAST:event_SearchIconLActionPerformed

    private void SearchIconRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIconRActionPerformed
        TaskCreateUpdateUI taskcreate = new TaskCreateUpdateUI();
        taskcreate.setVisible(true);
    }//GEN-LAST:event_SearchIconRActionPerformed

    private void MaximizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaximizeButtonActionPerformed
        LeftProjectPanel.setVisible(false);
        RightProjectPanel.setVisible(false);
        MaximizeButton.setVisible(false);
        MinimizeButtonM.setVisible(false);
        DeMaximizeButton.setVisible(true);
        DeMinimizeButtonL.setVisible(true);
        DeMinimizeButtonR.setVisible(true);
    }//GEN-LAST:event_MaximizeButtonActionPerformed

    private void SortLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortLActionPerformed
        SortUI sortL = new SortUI();
        sortL.setVisible(true);
    }//GEN-LAST:event_SortLActionPerformed

    private void MinimizeButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonLActionPerformed
        LeftProjectPanel.setVisible(false);
        DeMinimizeButtonL.setVisible(true);
        MaximizeButton.setVisible(false);
    }//GEN-LAST:event_MinimizeButtonLActionPerformed

    private void sortRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortRActionPerformed
        SortUI sortR = new SortUI();
        sortR.setVisible(true);
    }//GEN-LAST:event_sortRActionPerformed

    private void DeMinimizeButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMinimizeButtonLActionPerformed
        LeftProjectPanel.setVisible(true);
        DeMinimizeButtonL.setVisible(false);
        MaximizeButton.setVisible(true);
    }//GEN-LAST:event_DeMinimizeButtonLActionPerformed

    private void DeMinimizeButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMinimizeButtonMActionPerformed
        MidProjectPanel.setVisible(true);
        DeMinimizeButtonM.setVisible(false);
    }//GEN-LAST:event_DeMinimizeButtonMActionPerformed

    private void DeMinimizeButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMinimizeButtonRActionPerformed
        RightProjectPanel.setVisible(true);
        DeMinimizeButtonR.setVisible(false);
        MaximizeButton.setVisible(true);
    }//GEN-LAST:event_DeMinimizeButtonRActionPerformed

    private void DeMaximizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeMaximizeButtonActionPerformed
        //TODO handle condition when maximize then deminimize both left and right and the demaximize still there
        LeftProjectPanel.setVisible(true);
        RightProjectPanel.setVisible(true);
        DeMaximizeButton.setVisible(false);
        MaximizeButton.setVisible(true);
        MinimizeButtonM.setVisible(true);
        DeMinimizeButtonL.setVisible(false);
        DeMinimizeButtonR.setVisible(false);
    }//GEN-LAST:event_DeMaximizeButtonActionPerformed

    private void MinimizeButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonMActionPerformed
        MidProjectPanel.setVisible(false);
        DeMinimizeButtonM.setVisible(true);
    }//GEN-LAST:event_MinimizeButtonMActionPerformed

    private void MinimizeButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonRActionPerformed
        RightProjectPanel.setVisible(false);
        DeMinimizeButtonR.setVisible(true);
        MaximizeButton.setVisible(false);
    }//GEN-LAST:event_MinimizeButtonRActionPerformed

    private void AddTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskButtonActionPerformed
        TaskCreate taskcreate = new TaskCreate();
        taskcreate.setVisible(true);
    }//GEN-LAST:event_AddTaskButtonActionPerformed

    private void FilterLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterLActionPerformed
        FilterUI filterL = new FilterUI();
        filterL.setVisible(true);
        /*filterL.FilterButton.addActionListener(new ActionListener() {
					public void actionPerformed(ActionEvent e) {
						if (filterL.FilterOption1.isSelected()) {
							total = total - 5;
						} 
						
						if (filterL.FilterOption2.isSelected()) {
							total = total - 10;
						} 
						
						if (filterL.FilterOption3.isSelected()) {
							total = total - 15;
						} 
						
						if (filterL.FilterOption4.isSelected()) {
							total = total - 20;
						} 	
						
						testFilterText.setText(Double.toString(total));
						filterL.dispose();
					}
				});*/
    }//GEN-LAST:event_FilterLActionPerformed

    private void filterRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterRActionPerformed
        FilterUI filterR = new FilterUI();
        filterR.setVisible(true);
        /*filterL.FilterButton.addActionListener(new ActionListener() {
					public void actionPerformed(ActionEvent e) {
						if (filterL.FilterOption1.isSelected()) {
							total = total - 5;
						} 
						
						if (filterL.FilterOption2.isSelected()) {
							total = total - 10;
						} 
						
						if (filterL.FilterOption3.isSelected()) {
							total = total - 15;
						} 
						
						if (filterL.FilterOption4.isSelected()) {
							total = total - 20;
						} 	
						
						testFilterText.setText(Double.toString(total));
						filterL.dispose();
					}
				});*/
    }//GEN-LAST:event_filterRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTaskButton;
    private javax.swing.JButton DeMaximizeButton;
    private javax.swing.JButton DeMinimizeButtonL;
    private javax.swing.JButton DeMinimizeButtonM;
    private javax.swing.JButton DeMinimizeButtonR;
    private javax.swing.JButton FilterL;
    private javax.swing.JPanel LeftProjectPanel;
    private javax.swing.JButton MaximizeButton;
    private javax.swing.JPanel MidProjectPanel;
    private javax.swing.JButton MinimizeButtonL;
    private javax.swing.JButton MinimizeButtonM;
    private javax.swing.JButton MinimizeButtonR;
    private javax.swing.JScrollPane OnBacklogPanel;
    private javax.swing.JScrollPane OnFinishPanel;
    private javax.swing.JScrollPane OnGoingPanel;
    private javax.swing.JScrollPane OnTakenPanel;
    private javax.swing.JPanel RightProjectPanel;
    private javax.swing.JTextField SearchBarL;
    private javax.swing.JTextField SearchBarR;
    private javax.swing.JButton SearchIconL;
    private javax.swing.JButton SearchIconR;
    private javax.swing.JButton SortL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton filterR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton sortR;
    // End of variables declaration//GEN-END:variables
    private BoardUI backlog;
    private BoardUI taken;
    private BoardUI ongoing;
    private BoardUI finish;

    public void setPMinimizeHidden() {
        DeMinimizeButtonL.setVisible(false);
        DeMinimizeButtonR.setVisible(false);
        DeMinimizeButtonM.setVisible(false);
        DeMaximizeButton.setVisible(false);
    }

    public void addTask() {
        TaskHold.loadTask();
        backlog = new BoardUI(BoardType.BACKLOG);
        taken = new BoardUI(BoardType.TAKEN);
        ongoing = new BoardUI(BoardType.ONGOING);
        finish = new BoardUI(BoardType.FINISH);

        OnBacklogPanel.setViewportView(backlog);
        OnTakenPanel.setViewportView(taken);
        OnGoingPanel.setViewportView(ongoing);
        OnFinishPanel.setViewportView(finish);
    }
}
