/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout.views.project;

import common.Project.Projecthold;
import common.Project.Project;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import layout.views.screen.ScreenUI;
import common.User.CurrentUserhold;

/**
 *
 * @author tug70
 */
public class ProjectUICreateUpdate extends javax.swing.JFrame {

    DateFormat df = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form ProjectUICreate1
     */
    public ProjectUICreateUpdate() {
        initComponents();
        this.getErrorText().setVisible(false);
        if(CurrentUserhold.getUser().getAccessRange()<3){
            this.getDeleteButton().setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameString = new javax.swing.JTextField();
        IDint = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        summaryLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        teamLabel = new javax.swing.JLabel();
        startDateDate = new javax.swing.JTextField();
        dueDateDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        summaryString = new javax.swing.JTextArea();
        createUpdateLabel = new javax.swing.JLabel();
        buttonSection = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        teamDropDown = new javax.swing.JComboBox<>();
        errorText = new javax.swing.JLabel();
        teamScrollPane = new javax.swing.JScrollPane();
        addedUsers = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Project");
        setLocation(new java.awt.Point(100, 100));

        IDint.setEditable(false);

        nameLabel.setText("Name:");

        startDateLabel.setText("Start:");

        endDateLabel.setText("End:");

        summaryLabel.setText("Summary:");

        IDLabel.setText("ID:");

        teamLabel.setText("Team:");

        summaryString.setColumns(20);
        summaryString.setRows(5);
        jScrollPane1.setViewportView(summaryString);

        createUpdateLabel.setText("CREATE PROJECT");

        submitButton.setText("add");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonSectionLayout = new javax.swing.GroupLayout(buttonSection);
        buttonSection.setLayout(buttonSectionLayout);
        buttonSectionLayout.setHorizontalGroup(
            buttonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonSectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addGap(6, 6, 6))
        );
        buttonSectionLayout.setVerticalGroup(
            buttonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonSectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(deleteButton))
                .addContainerGap())
        );

        teamDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        errorText.setForeground(new java.awt.Color(255, 51, 51));
        errorText.setText("error");

        addedUsers.setColumns(20);
        addedUsers.setRows(5);
        teamScrollPane.setViewportView(addedUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(createUpdateLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(startDateLabel)
                            .addComponent(endDateLabel)
                            .addComponent(summaryLabel)
                            .addComponent(IDLabel)
                            .addComponent(teamLabel))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDint, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(teamDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameString)
                                    .addComponent(startDateDate, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(dueDateDate, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(teamScrollPane))))
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(errorText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createUpdateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorText)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameLabel))
                                .addGap(40, 40, 40))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(startDateLabel)
                                .addComponent(startDateDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(endDateLabel)
                        .addComponent(dueDateDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(summaryLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDLabel)
                    .addComponent(IDint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamLabel)
                    .addComponent(teamDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(buttonSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //TODO handle case of error
        //TODO handle adding user
        //add that new project Object to the projecthold ArrayList
        Project addProject = createProjectFromFields();

        //TODO refactor this method to make better sense and reduce time complexity
        //check if it's update or not
        boolean updated = false;
        //for updating new project
        for (int i = 0; i < Projecthold.getProjects().size(); i++) {
            if (addProject.getID() == Projecthold.getProjects().get(i).getID()) {
                //replace the project at i
                Projecthold.getProjects().set(i, addProject);
                updated = true;
                break;
            }
        }
        //for inserting new project
        if (addProject.getID() != -1 && updated == false) {
            Projecthold.insert(addProject);
        }
        //rerender the dropdown in screenUI
        ScreenUI.getProjectUI().renderUI();
        //Close the Project create window
        this.dispose();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        for (int i = 0; i < Projecthold.getProjects().size(); i++) {
            if (Integer.parseInt(this.getIDint().getText()) == Projecthold.getProjects().get(i).getID()) {
                Projecthold.delete(Projecthold.getProjects().get(i));
                break;
            }
        }
        //rerender the dropdown in screenUI
        ScreenUI.getProjectUI().renderUI();
        //Close the Project create window
        this.dispose();
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDint;
    private javax.swing.JTextArea addedUsers;
    private javax.swing.JPanel buttonSection;
    private javax.swing.JLabel createUpdateLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField dueDateDate;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JLabel errorText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameString;
    private javax.swing.JTextField startDateDate;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel summaryLabel;
    private javax.swing.JTextArea summaryString;
    private javax.swing.JComboBox<String> teamDropDown;
    private javax.swing.JLabel teamLabel;
    private javax.swing.JScrollPane teamScrollPane;
    // End of variables declaration//GEN-END:variables
    public Project createProjectFromFields() {
        try {
            //get all the attributes to insert in Project class
            String name = this.getNameString().getText();
            Date startDate = new SimpleDateFormat("dd/MM/yyyy").parse(this.getStartDateDate().getText());
            Date dueDate = new SimpleDateFormat("dd/MM/yyyy").parse(this.getDueDateDate().getText());
            Date createDate = new Date();
            String summary = this.getSummaryString().getText();
            int ID = Integer.parseInt(this.getIDint().getText());
            int[] team=new int[1];
            team[0]=CurrentUserhold.getUser().getID();
            
            //add all attribute to a new project Object
            Project addProject = new Project(ID, name, createDate, startDate, dueDate, summary, team);
            return addProject;
        } catch (Exception e) {
            System.out.println(e);
            return new Project(-1);
        }

    }

    public void setUpdateInformation(Project project) {
        this.setIDint(project.getID());
        this.setDueDateDate(project.getDueDate());
        this.setStartDateDate(project.getStartDate());
        this.setSummaryString(project.getSummary());
        this.setNameString(project.getName());

    }

    /**
     * @return the IDint
     */
    public javax.swing.JTextField getIDint() {
        return IDint;
    }

    /**
     * @param IDint the IDint to set
     */
    public void setIDint(int IDint) {
        this.IDint.setText(String.valueOf(IDint));
    }

    /**
     * @return the endDateDate
     */
    public javax.swing.JTextField getDueDateDate() {
        return dueDateDate;
    }

    /**
     * @param endDateDate the endDateDate to set
     */
    public void setDueDateDate(Date endDateDate) {
        this.dueDateDate.setText(df.format(endDateDate));
    }

    /**
     * @return the nameString
     */
    public javax.swing.JTextField getNameString() {
        return nameString;
    }

    /**
     * @param nameString the nameString to set
     */
    public void setNameString(String nameString) {
        this.nameString.setText(nameString);
    }

    /**
     * @return the startDateDate
     */
    public javax.swing.JTextField getStartDateDate() {
        return startDateDate;
    }

    /**
     * @param startDateDate the startDateDate to set
     */
    public void setStartDateDate(Date startDateDate) {
        this.startDateDate.setText(df.format(startDateDate));
    }

    /**
     * @return the summaryString
     */
    public javax.swing.JTextArea getSummaryString() {
        return summaryString;
    }

    /**
     * @param summaryString the summaryString to set
     */
    public void setSummaryString(String summaryString) {
        this.summaryString.setText(summaryString);
    }

    /**
     * @return the teamDropDown
     */
    public javax.swing.JComboBox<String> getTeamDropDown() {
        return teamDropDown;
    }

    /**
     * @param teamDropDown the teamDropDown to set
     */
    public void setTeamDropDown(javax.swing.JComboBox<String> teamDropDown) {
        this.teamDropDown = teamDropDown;
    }

    /**
     * @return the createUpdateLabel
     */
    public javax.swing.JLabel getCreateUpdateLabel() {
        return createUpdateLabel;
    }

    /**
     * @param createUpdateLabel the createUpdateLabel to set
     */
    public void setCreateUpdateLabel(String createUpdateLabel) {
        this.createUpdateLabel.setText(createUpdateLabel);
    }

    /**
     * @return the deleteButton
     */
    public javax.swing.JButton getDeleteButton() {
        return deleteButton;
    }

    /**
     * @param deleteButton the deleteButton to set
     */
    public void setDeleteButton(javax.swing.JButton deleteButton) {
        this.deleteButton = deleteButton;
    }

    /**
     * @return the errorText
     */
    public javax.swing.JLabel getErrorText() {
        return errorText;
    }

    /**
     * @param errorText the errorText to set
     */
    public void setErrorText(javax.swing.JLabel errorText) {
        this.errorText = errorText;
    }

    /**
     * @return the submitButton
     */
    public javax.swing.JButton getSubmitButton() {
        return submitButton;
    }

    /**
     * @param submitButton the submitButton to set
     */
    public void setSubmitButton(String submitButton) {
        this.submitButton.setText(submitButton);
    }
}
